<?php include ("Section/Slider.php")?>
<?php include ("Section/Covid.php")?>
<?php include ("Section/OutProduct.php")?>
<?php include ("Section/Services.php")?>
<?php include ("Section/Section_4.php")?>
<?php include ("Section/InTro.php")?>
<?php include ("Section/TuyenDung.php")?>
<?php include ("Section/Video.php")?>
<?php include ("Section/Event.php")?>